### PR TITLE
Support Django 2.2

### PR DESCRIPTION
**Pull request by tim-schilling**

### CODE REVIEW

**Comment by jheld** [comment]
Awesome! So fast. Can you also please adjust `travis.yml` to add another env and set of exclusion cases for `<2.3`? And if we decide to do `<3.0`, then swap it to that.

**Comment by tim-schilling** [comment]
Can do. Is there a reason why the exclusions for 2.7-3.5 have upper bounds? It's extremely unlikely that Django will backport support for those.

**Comment by tim-schilling** [comment]
My mistake. I didn't understand how to set up the Travis configs.

**Comment by tim-schilling** [comment]
I squashed the commits related to the Django 2.2 change. I left the commit deleting tox.ini on its own. I'm not sure how you like to maintain git history.

**Comment by jheld** [comment]
No worries, re:travis config. It takes some times to get used to it.

Is the `tox.ini` actually unused? I thought the makefile for testing was capable of using it (maybe not).

**Comment by tim-schilling** [comment]
> Is the tox.ini actually unused?

I couldn't find any references to tox in the repository. And the make file uses `python manage.py test` for running tests which is the same command that Travis uses and those worked fine.

If you'd feel more comfortable me removing that commit I can. I only looked into it because `tox.ini`'s most recent version of python was 3.3 and I thought that was weird.

**Comment by jheld** [comment]
Right, right. Yes, let's remove the commit for now. I'm thrilled that you were curious about it, though. I'm fairly conservative with making changes (unless needed/so much better).

**Comment by tim-schilling** [comment]
Sounds good and done.

**Comment by jheld** [comment]
Merged.  @tim-schilling do you mind if this new version is `1.11.0rc1`? I'm not positive there are no django 2.2 bugs here.

**Pull request merged**
