### PR TITLE
make rest client work with the v6 twilio library

### PR DESCRIPTION
**Pull request by mulka**

### CODE REVIEW

**Comment by audrummer15** [comment]
Is there a reason for holding off on this merge?

**Comment by tprestegard** [comment]
I definitely support this, django-twilio is non-functional for recent versions of twilio-python.  Getting a new version on PyPi would also be great.

**Comment by jheld** [comment]
master is capable of working with the new version (our server runs it). But this does improve the support and cleans things up further. I also wonder why this wouldn't be merged?

**Comment by mulka** [comment]
I've pushed a forked version of django-twilio to pypi as django-twilio2 which supports v6 of the twilio library

**Comment by rdegges** [comment]
Hey guys, I've commented on other threads. But if you'd like to help maintain this so you don't need to rename it I'm happy to give over edit access! Please hit me up @mulka!

**Comment by jheld** [comment]
Hi all,

I'm a new contributor/maintainer of this project. Thanks @rdegges. I'll be looking through the issues and PRs as quickly as I can. Please provide any updates (usage, issues, workarounds) that you may have, or patches, as PRs; otherwise it's in order of importance, followed by morality.

I look forward to getting this and any other twilio compat in shortly.

**Pull request merged**
