### PR TITLE
Get test suite passing on django 1.10.6

### PR DESCRIPTION
**Pull request by boardman**
This PR is the minimum i needed to do to get the test suite passing on django 1.10.6

Apologies if i have done this wrong, should i have just included the one change to the library, excluding the other 3 commits needed to get the test suite running?

Thanks

### CODE REVIEW

**Comment by km-pg** [comment]
The master branch seems to be ahead of develop. Specifically, there is a commit in master that might fix the travis ci build that is broken here. Maybe consider rebasing off of develop to see if it fixes the travis ci build.

**Comment by jheld** [comment]
Any progress on this?

**Comment by mulka** [comment]
I've pushed a forked version of django-twilio to pypi as django-twilio2 which supports django 1.10

**Comment by jheld** [comment]
I'll be looking through this in the short term. Thanks for your work!

**Pull request merged**
