### PR TITLE
Update requirement.txt to allow Django 2.1

### PR DESCRIPTION
**Pull request by tim-schilling**

### CODE REVIEW

**Comment by jheld** [comment]
Thank you! Can you change this to point to the `develop` branch, though?
Not sure how this escaped the last release.

**Comment by tim-schilling** [comment]
No problem. Thanks for the quick response!

**Comment by jheld** [comment]
@tim-schilling ok, I've released `0.9.3` to PyPI. Please let me know if you have any other install or runtime issues!

**Comment by tim-schilling** [comment]
Thanks. It wasn't an actual issue but I noticed the discrepancy.

**Pull request merged**
