### PR TITLE
Allow Django 5.x in setup.py

### PR DESCRIPTION
**Pull request by calebsyring**
Refs #238

Once this is released, #238 should be closed.

### CODE REVIEW

**Comment by calebsyring** [comment]
I'm not sure where these checks are configured :point_up:, but assuming the second number in parentheses above is the django version, we may want to add a 5.0 check.

**Comment by jheld** [comment]
Oh yes good call. They are in: https://github.com/rdegges/django-twilio/blob/413f926e8a7ca6bb17a11469c47ea33a2a901b9f/.github/workflows/build.yml#L13

**Comment by calebsyring** [comment]
Okay. Took some trial-and-error, but I updated the build file. Also updated the readme while I was at it. Should be GTG.

**Comment by calebsyring** [comment]
Actually, hold off.

**Comment by calebsyring** [comment]
> Actually, hold off.

I wanted to update setup.py to change the django version requirement based on the python version. That's done now.

**Comment by jheld** [comment]
OK, the alpha version is now on PyPI. Once you've tested this in some reasonably confident way, let me know and I'll cut the official release!

**Comment by aaronmader** [comment]
0.14.3.4a1 appears to be working well, for my projects, though I'm currently only making use of:
`from django_twilio.decorators import twilio_view`, and
`from django_twilio.client import twilio_client`

**Pull request merged**
